name: tech_finances
description: Projeto flutter destinado a disciplina Projeto Integrador.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path:
  intl: ^0.17.0
  pie_chart: ^5.4.0
  syncfusion_flutter_charts: ^20.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/receita.png
    - images/despesa.png